version: '3'

services:
  todotests:
    image: todotests
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000

  todofront:
    image: todofrontend
    depends_on:
      - "todoback"
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001

  todoback:
    image: todobackend
    ports:
      - 3001:3001